### ISSUE TITLE
How to update an IdentityUser within CosmosDB?

### ISSUE THREAD

**Issue by etriebe** [MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb#24]
### Discussed in https://github.com/MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **etriebe** February  2, 2024</sup>
I'm trying to update objects within CosmosDB just like I've done with other objects but I get an exception when I do so. I'm only updating username but I get this error. 

```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 2aaf5d6d-4433-4488-8f52-905849797594; Reason: (Message: {"Errors":["One of the specified inputs is invalid"]}
ActivityId: 2aaf5d6d-4433-4488-8f52-905849797594, Request URI: /apps/8ce365e5-ba15-438a-a471-07d6b564394d/services/22cbecbc-8764-4e5b-b75b-76fa9b95216b/partitions/fd5ad3bd-b31c-455f-868a-f9c2ca0c97c2/replicas/133265169497594395p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.31.4);
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Documents.StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)
   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)

  This exception was originally thrown at this call stack:
    [External Code]
    Pickem.Shared.Utilities.Data.IdentityDBUtils.UpdateUserAsync(Microsoft.AspNetCore.Identity.IdentityUser) in IdentityDBUtils.cs
```</div>

**Comment by toiyabe** [comment]
Hello etriebe!
Sorry for the late reply. Give me a day or two to research this and get back to you.
Thanks!
-Eric

**Comment by toiyabe** [comment]
Meanwhile, this might help. I have a test for setting the username. This may not be what you want to do since it is not exactly the same as what you are trying to do.

See below to see if this might help:

// This method is tested with SetUserNameAsync().
        [TestMethod()]
        public async Task SetNormalizedUserNameAsyncTest()
        {
            // Arrange
            using var userStore = _testUtilities.GetUserStore();
            var user = await GetMockRandomUserAsync(userStore);
            var newEmail = $"A{GetNextRandomNumber(111, 9999).ToString()}@foo.com";

            // Act
            await userStore.SetNormalizedUserNameAsync(user, newEmail.ToUpper());

            // Assert
            var user2 = await userStore.FindByIdAsync(user.Id);
            Assert.AreEqual(newEmail.ToUpper(), user2.NormalizedUserName);
        }

**Comment by etriebe** [comment]
I had been using Cosmos DB functions to do an UpsertItemAsync.

```
ItemResponse<IdentityUser> udpatedUser = await this.container.UpsertItemAsync<IdentityUser>(user, new PartitionKey(user.Id));
```

**Comment by etriebe** [comment]
What is that _testUtilities object type?

**Comment by toiyabe** [comment]
[TestUtilities ](https://github.com/MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb/blob/main/AspNetCore.Identity.CosmosDb.Tests.Net7/TestUtilities.cs) is a class used to setup unit tests in the project [AspNetCore.Identity.CosmosDb.Tests.csproj](https://github.com/MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb/blob/main/AspNetCore.Identity.CosmosDb.Tests.Net7/AspNetCore.Identity.CosmosDb.Tests.csproj).  It does things like gets configuration from secrets, has test user IDs and email addresses, gets database options, mocks up role and user store and more.  The unit tests run through various functions to make sure things are working right. Often it is handy to look at a unit test to see how something is done.

**Comment by toiyabe** [comment]
I'm thinking back to your question above about changing user names. 

With the UserManager object there is a method called SetUserNameAsync.  The benefit of using this is it saves the new user name, **_plus_** the "normalized" value.

This code snipped from the unit tests might be more to what you need:

```c#
 [TestMethod]
 public async Task SetUserNameAsyncTest()
 {
     // Arrange
     using var userManager = GetTestUserManager(_testUtilities.GetUserStore());
     var user = await GetTestUser(userManager);
     var userName = "Az" + user.UserName;

     // Act
     await userManager.SetUserNameAsync(user, userName);

     // Assert
     user = await userManager.FindByIdAsync(user.Id);
     Assert.IsTrue(user.UserName == userName);
 }
```

The "GetTestUserManager" method above is in the TestUtilities class. It mocks a test user.

**Comment by etriebe** [comment]
Gotcha, yeah, I'm trying out using UserManager now. Guessing that'll fix
things for me! Thank you!

**Comment by etriebe** [comment]
That worked! Thanks so much!
